name: BloodMoney
version: 1.1.0
main: net.thereturningvoid.bloodmoney.BloodMoney

softdepend: [Vault]

commands:
  bmreloadconfig:
    description: Reloads the BloodMoney configuration file (plugins/BloodMoney/config.yml)
    usage: /<command>
