name: BloodMoney
version: 0.0.1-SNAPSHOT
main: net.thereturningvoid.bloodmoney.BloodMoney

softdepend: [Vault]

commands:
  bmreloadconfig:
    description: Reloads the BloodMoney configuration file (plugins/BloodMoney/config.yml)
    usage: /<command>
